---
abstract: 'Allows RT to do authentication via PAUSE (pause.perl.org)'
author:
  - 'Thomas Sibley <trs@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.89'
license: 'GPL version 2'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Authen-PAUSE
no_index:
  directory:
    - html
    - inc
requires:
  HTTP::Request: 0
  LWP::UserAgent: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.02
